name: Build HashCheck Installer

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Add MSBuild to PATH
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      # 3. Setup NuGet
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      # 4. Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore HashCheck.sln

      # 5. Build x86
      - name: Build x86
        run: msbuild HashCheck.sln /p:Configuration=Release /p:Platform=Win32 /p:OutDir=../Release/Win32/

      # 6. Build x64
      - name: Build x64
        run: msbuild HashCheck.sln /p:Configuration=Release /p:Platform=x64 /p:OutDir=../Release/x64/

      # 7. Folders
      - name: Prepare folders for NSIS
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path Release/Win32
          New-Item -ItemType Directory -Force -Path Release/x64

          Copy-Item -Path "Release/x64/HashCheck.dll" -Destination "Release/x64/" -ErrorAction SilentlyContinue
          Copy-Item -Path "Release/Win32/HashCheck.dll" -Destination "Release/Win32/" -ErrorAction SilentlyContinue

      # 8. Install NSIS
      - name: Install NSIS
        run: choco install nsis -y

      # 9. Compile NSIS Installer
      - name: Compile NSIS Installer
        shell: cmd
        run: '"C:\Program Files (x86)\NSIS\makensis.exe" installer\HashCheck.nsi'

      # 10. Upload Installer
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: HashCheck-Setup
          path: installer/*.exe