name: Build HashCheck Installer

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    # Kompilacja x86 - używamy Get-ChildItem, aby PowerShell sam znalazł ścieżkę
    - name: Build x86
      run: |
        $proj = (Get-ChildItem -Filter "HashCheck.vcxproj" -Recurse).FullName[0]
        msbuild $proj /p:Configuration=Release /p:Platform=Win32 /p:OutDir="../Release/Win32/"

    # Kompilacja x64
    - name: Build x64
      run: |
        $proj = (Get-ChildItem -Filter "HashCheck.vcxproj" -Recurse).FullName[0]
        msbuild $proj /p:Configuration=Release /p:Platform=x64 /p:OutDir="../Release/x64/"

    # Kompilacja instalatora NSIS
    - name: Compile NSIS Installer
      run: |
        $nsi = (Get-ChildItem -Filter "HashCheck.nsi" -Recurse).FullName[0]
        makensis $nsi

    # Przesłanie gotowego instalatora
    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: HashCheck-Setup-Package
        path: "**/HashCheck*.exe"